# Generated by Django 3.2 on 2022-03-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('customer_full_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_postcode', models.CharField(max_length=20)),
                ('customer_town_or_city', models.CharField(max_length=40)),
                ('customer_street_address1', models.CharField(max_length=80)),
                ('customer_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('customer_county', models.CharField(blank=True, max_length=80, null=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('purchase_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LinesInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='checkout.order')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
            ],
        ),
    ]
