# Generated by Django 3.2 on 2022-03-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('checkout', '0002_auto_20220307_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customeraccount'),
        ),
    ]
