# Generated by Django 3.2 on 2022-02-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=254)),
                ('artist', models.CharField(max_length=254)),
                ('record_label', models.CharField(max_length=254)),
                ('release_year', models.CharField(max_length=4)),
                ('hot_pick', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('mint', 'M'), ('near_mint', 'NM'), ('very_good', 'VG'), ('good', 'G'), ('fair', 'F'), ('poor', 'P')], default='mint', max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tracklist', models.TextField()),
                ('description', models.TextField()),
                ('has_link', models.BooleanField(default=False)),
                ('link_to_music', models.URLField(blank=True, max_length=1024, null=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.genre')),
            ],
        ),
    ]
